"""empty message

Revision ID: 59895301cc30
Revises: c5a868c03e18
Create Date: 2026-01-21 09:41:28.385221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59895301cc30'
down_revision = 'c5a868c03e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_follow_pair', ['user_from_id', 'user_to_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('uq_follow_pair', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
